version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8004:8080"
    networks:
      - projetdevops_app-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"  
    networks:
      - projetdevops_app-network
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: 4se21
    volumes:
      - mysql_data:/var/lib/mysql

  test-mysql:
    image: mysql:latest
    networks:
      - projetdevops_app-network
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 4se21  
    volumes:
      - test_mysql_data:/var/lib/mysql

networks:
  projetdevops_app-network:
    driver: bridge

volumes:
  mysql_data:
  test_mysql_data:
