version: "3"
services:
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
  
    environment:
      - MYSQL_DATABASE=4se21 
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  springboot:
    image: yassine121/5se2:latest
    ports:
      - "8082:8080"
   
    depends_on:
      - mysqldb

