services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: ramzi
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot:
    depends_on:
      - mysql
    image: ramzizarg/ramzizargelayoun-devops_project:latest
    container_name: spring-boot
    restart : always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8082:8082"

volumes:
  mysql_data:
