version: "3.8"

services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 4se21          # Nom de la base de données à créer
      MYSQL_ROOT_PASSWORD: ""         # Mot de passe vide pour l'utilisateur root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:                     # Pour s'assurer que MySQL est prêt avant de lancer le service Spring Boot
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 3

  springboot:
    image: yassine121/5se2:latest
    ports:
      - "8082:8080"
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql_data:
